- name: variables
  hosts: localhost
  vars: 
    course: udemy
    price: 100$
    language: python
  tasks: 
    - name: print information about training
      ansible.builtin.debug:
       msg: "im taking training from {{course}} and the price is {{price}} for only{{language}}"

- name: variables in numbers
  hosts: localhost
  vars: 
    A: 10
    B: 60
    c : 70
  tasks:  
    - name: print the values
      ansible.builtin.debug:
         msg: "if {{A}} is added to {{B}} and what is the whole value of {{C}}"