 - name: task level preference variables
   hosts: localhost
   vars:  
     Course: "join Devops"
     Con: "tools"
     Fee: "30k"
   tasks: 
    - name: print override information
      vars:  # Task level variable that means it overides and give the priority to task level first after other.
        Course: "Intellipath"
        Con: "Devops"
      ansible.builtin.debug: 
         msg: "Hi we are learning course in {{Course}} platform with main content {{Con}}, and the payment fee is {{Fee}}."
    
    - name: print information
      ansible.builtin.debug: 
         msg: "Hi we are learning course in {{Course}} platform with main content {{Con}}, and the payment fee is {{Fee}}."
    