- name: variables from inventory
  hosts: localhost
  tasks:
    - name: print information
      ansible.builtin.debug:
         msg:" Hi, we are learning course {{Cou}},
                from {{Onl}},and duration is {{Dur}}."