- name: data Types
  hosts: localhost
  vars:
   Course: "Devops with aws" # string data type
   Tools: # List
   - Linux
   - Ansible
   - Shell
   Experience: # Map ot Dictionary
     Devops:3
     Aws:2
     Azure:1
   RealProject: true # Boolean data type
  tasks:
   - name: print the All data Types
     ansible.builtin.debug:
      msg: " Course: {{Course}}, Tools covered {{Tools}}, Experience is: {{Experience}}, 
               is rreal project {{RealProject}}."


    