- name: check number
  hosts: localhost
  vars_prompt:
   - name: number
     prompt: please enter any number
     private: No

  tasks:
   - name: number is less than 20
     ansible.builtin.debug:
       msg: "number is {{number}} is less than 20"
       when: number | int < 20

   - name: number is greater than or equal to 20
     ansible.builtin.debug:
       msg: "number is greater than or equal 20"
       when: number | int > = 20