- name: Demo on loops
  hosts: localhost
  tasks:  
    - name: Print loop of names
      ansible.builtin.debug:
        msg: " Hello list of vegies: {{item}}"
      loop:
       - brinjal
       - carrot
       - beetroot
       - tomatoes
