- name: install and run Nginx
  hosts: web
  become: yes # equal to -b in adhoc commands, giving root acess
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
     name: nginx
     state: latest
  - name: start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes